<?php

define('MINECRAFT_JCOINS_ENABLED', false);
define('MINECRAFT_JCOINS_KEY', '');
define('MINECRAFT_JCOINS_FLOODGATE_RESETTIME', 0);
define('MINECRAFT_JCOINS_FLOODGATE_MAXREQUESTS', 0);
define('JCOINS_ALLOW_NEGATIVE', false);
